version: '3.0'

networks:
  laravel_network:
    driver: bridge

volumes:
  db_server1_data:
    driver: local

  # Servidor MySQL
  db_server1:
    image: mysql:8.0
    container_name: db_server3
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_db
      MYSQL_PASSWORD: root
    ports:
      - "3311:3306"
    volumes:
      - db_server1_data:/var/lib/mysql
    networks:
      - laravel_network

  # Servidor de Email
  email-service:
      # dir local
    image: email-service  
    container_name: email-service
    restart: unless-stopped
    volumes:
      - ./kafka-service:/var/www/html
    environment:
      # puertos internos
      - DB_CONNECTION=mysql
      - DB_HOST=db_server3
      - DB_PORT=3306
      - DB_DATABASE=order_db
      - DB_USERNAME=root
      - DB_PASSWORD=root

      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - FILESYSTEM_DISK=local
      - QUEUE_CONNECTION=database
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120

      - APP_ENV=local
      - APP_KEY=base64:ywmpbc5TT+QGUOPPlwUDwZJKqQUX0HqDFlh/uRsjh7c=
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - JWT_SECRET=Z7Pc4p6GurcEanHw3tOUjSmyvX1PzkzKp7R17Awkeu0wODoEfi9ci30pOlQpi7Go
    ports:
      - "8879:80"
    depends_on:
      - db_server1
    networks:
      - laravel_network  
